spring.application.name=siblhish-api

# Database Configuration
# Railway provides DATABASE_URL in format: postgresql://user:password@host:port/database
# Spring Boot needs JDBC format: jdbc:postgresql://host:port/database
# We use individual variables that Railway provides
spring.datasource.url=jdbc:postgresql://shortline.proxy.rlwy.net:31518/railway
spring.datasource.username=postgres
spring.datasource.password=hdemCrQDanzukBeYYdnWcUDTHpWGTSTu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# API Configuration
server.servlet.context-path=/api/v1
server.port=${PORT:8080}

# Firebase (notifications push) : variable FIREBASE_SERVICE_ACCOUNT_JSON = contenu du JSON Service Account

# Logging
logging.level.root=INFO
logging.level.ma.siblhish=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO
logging.level.org.springframework.web=INFO

