spring.application.name=siblhish-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://shortline.proxy.rlwy.net:31518/railway
spring.datasource.username=postgres
spring.datasource.password=hdemCrQDanzukBeYYdnWcUDTHpWGTSTu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# API Configuration
server.servlet.context-path=/api/v1
server.port=8081

# Firebase Configuration
# Pour l'API V1, utiliser un Service Account JSON
# 1. Aller dans Firebase Console → Paramètres du projet → Comptes de service
# 2. Générer une nouvelle clé privée et télécharger le fichier JSON
# 3. Placer le fichier dans src/main/resources/firebase-service-account.json
firebase.service-account-classpath=firebase/siblhish-app-firebase-adminsdk-fbsvc-05ce4c5f95.json
# firebase.service-account-path=/chemin/vers/firebase-service-account.json

# Logging
logging.level.root=INFO
logging.level.ma.siblhish=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web=INFO

