spring.application.name=siblhish-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://shortline.proxy.rlwy.net:31518/railway
spring.datasource.username=postgres
spring.datasource.password=hdemCrQDanzukBeYYdnWcUDTHpWGTSTu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# API Configuration
server.servlet.context-path=/api/v1
server.port=8081

