package ma.siblhish.enums;

public enum TypeNotification {
    DAILY_REPORT,
    MONTHLY_REPORT,
    RECURRING_TRANSACTION,
    RECURRING_BUDGET,
    RECURRING_SCHEDULED_PAYMENT,
    PAYMENT_REMINDER,
    PAYMENT_MARKED_AS_PAID,
    PAYMENT_DUE_TODAY,
    PAYMENT_OVERDUE,
    BUDGET_WARNING,
    BUDGET_EXCEEDED
}
